# Multi-reviewer workflow configuration
# Uses Codex for planning and Claude for review by default.
# With --claude flag, all agents are substituted with Claude variants.

agents:
  claude:
    command: "claude"
    args:
      - "-p"
      - "--output-format"
      - "stream-json"
      - "--verbose"
      - "--dangerously-skip-permissions"
    # Tools allowed for implementation-review (repo inspection)
    allowed_tools:
      - "Read"
      - "Glob"
      - "Grep"
      - "Bash"

  codex:
    command: "codex"
    args:
      - "exec"
      - "--json"
      - "--dangerously-bypass-approvals-and-sandbox"
      - "--skip-git-repo-check"
    allowed_tools: []

  gemini:
    command: "gemini"
    args:
      - "--output-format"
      - "json"
    allowed_tools: []

# Claude-mode configuration (activated with --claude flag)
# Defines Claude-specific agents, substitution rules, and phase overrides
claude_mode:
  # Claude agents for Claude-only mode (merge into agents map)
  agents:
    claude:
      command: "claude"
      args:
        - "-p"
        - "--output-format"
        - "stream-json"
        - "--verbose"
        - "--dangerously-skip-permissions"
      allowed_tools:
        - "Read"
        - "Glob"
        - "Grep"
        - "Write"
        - "Edit"
        - "Bash"
        - "WebSearch"
        - "WebFetch"
        - "Skill"
        - "Task"
      session_persistence:
        enabled: true
        strategy: conversation_resume

    claude-reviewer:
      command: "claude"
      args:
        - "-p"
        - "--output-format"
        - "stream-json"
        - "--verbose"
        - "--dangerously-skip-permissions"
      allowed_tools:
        - "Read"
        - "Glob"
        - "Grep"
        - "Bash"

  # Agent name substitutions when --claude is active
  substitutions:
    codex: claude
    gemini: claude

  # Override the reviewing phase to use specialized reviewers
  # Each reviewer uses a distinct skill with orthogonal focus
  #
  # Field meanings:
  # - `skill:` specifies which skill to invoke (determines methodology)
  # - `prompt:` (optional) provides additional review context if needed
  reviewing:
    agents:
      # The Adversarial Reviewer - challenges assumptions and finds failure modes
      # Runs first per research recommendation - if fundamental assumptions are wrong,
      # other reviews are wasted effort
      - agent: claude
        id: adversarial
        skill: plan-review-adversarial

      # The Operational Reviewer - validates production readiness
      - agent: claude
        id: operational
        skill: plan-review-operational

      # The Codebase Reviewer - ensures consistency with existing patterns
      - agent: claude
        id: codebase
        skill: plan-review-codebase

    aggregation: any_rejects
    sequential: true

# Codex-mode configuration (for codex-only workflow)
# Defines Codex-specific agents, substitution rules, and phase overrides
codex_mode:
  # Codex agents for Codex-only mode (merge into agents map)
  agents:
    codex:
      command: "codex"
      args:
        - "exec"
        - "--json"
        - "--dangerously-bypass-approvals-and-sandbox"
        - "--skip-git-repo-check"
      allowed_tools: []

    codex-reviewer:
      command: "codex"
      args:
        - "exec"
        - "--json"
        - "--dangerously-bypass-approvals-and-sandbox"
        - "--skip-git-repo-check"
      allowed_tools: []

  # Agent name substitutions when codex-only mode is active
  substitutions:
    claude: codex
    gemini: codex

  # Override the reviewing phase to use only codex
  reviewing:
    agents:
      - codex
    aggregation: any_rejects
    sequential: false

  # Override implementation to use codex/codex-reviewer
  implementation:
    implementing:
      agent: codex
      max_turns: 100
    reviewing:
      agent: codex-reviewer

# Gemini-mode configuration (for gemini-only workflow)
# Defines Gemini-specific agents, substitution rules, and phase overrides
gemini_mode:
  # Gemini agents for Gemini-only mode (merge into agents map)
  agents:
    gemini:
      command: "gemini"
      args:
        - "--output-format"
        - "json"
      allowed_tools: []

    gemini-reviewer:
      command: "gemini"
      args:
        - "--output-format"
        - "json"
      allowed_tools: []

  # Agent name substitutions when gemini-only mode is active
  substitutions:
    claude: gemini
    codex: gemini

  # Override the reviewing phase to use only gemini
  reviewing:
    agents:
      - gemini
    aggregation: any_rejects
    sequential: false

  # Override implementation to use gemini/gemini-reviewer
  implementation:
    implementing:
      agent: gemini
      max_turns: 100
    reviewing:
      agent: gemini-reviewer

workflow:
  planning:
    agent: codex
    max_turns: 200

  # All three agents review in parallel
  # Supports both simple format (agent name string) and extended format (object with custom prompt)
  reviewing:
    agents:
      - claude
      - codex
      #- gemini

      # Extended format example: Run multiple Claude instances with different focuses
      # Uncomment below to add specialized review passes:
      #- agent: claude
      #  id: claude-security    # Display name for logs/UI (defaults to agent name)
      #  prompt: |              # Appended to system prompt for this instance
      #    Focus your review on security concerns:
      #    - Authentication and authorization
      #    - Input validation and sanitization
      #    - Secrets and credential handling
      #
      #- agent: claude
      #  id: claude-architecture
      #  prompt: |
      #    Focus your review on architectural concerns:
      #    - Code organization and modularity
      #    - Design patterns and best practices
      #    - Performance implications
    aggregation: any_rejects
    sequential: true

  # Note: Revision phase uses the planning agent automatically.
  # This enables session continuity when using Claude with session_persistence enabled.

# Failure handling policy
# Controls how transient failures and recovery are handled
failure_policy:
  max_retries: 2 # Maximum retry attempts for transient failures
  backoff_secs: 5 # Backoff multiplier in seconds between retries
  # Action when all reviewers fail after retries:
  # - abort: Stop workflow with error (default)
  # - save_state: Save state for later recovery in TUI mode
  # - continue_without_review: Proceed to revision phase without reviews
  on_all_reviewers_failed: abort

# Implementation workflow configuration
# Runs after plan approval to implement the plan using JSON-mode agents
implementation:
  enabled: true
  max_iterations: 3
  implementing:
    agent: codex
    max_turns: 100
  reviewing:
    agent: claude
    # max_turns uses agent default

# Git worktree configuration
# When enabled, creates an isolated branch for each planning session
worktree:
  enabled: false  # Set to true to auto-create worktrees

# Optional: Post-implementation verification workflow
# Uncomment to enable verification after implementation
#verification:
#  enabled: true
#  max_iterations: 3
#  verifying:
#    agent: claude
#    max_turns: 10
#  fixing:
#    agent: claude
#    max_turns: 15
