# Multi-reviewer workflow configuration
# Uses Codex for planning and Claude for review by default.
# With --claude flag, all agents are substituted with Claude variants.

agents:
  claude:
    command: "claude"
    args:
      - "-p"
      - "--output-format"
      - "stream-json"
      - "--verbose"
      - "--dangerously-skip-permissions"
    # Tools allowed for implementation-review (repo inspection)
    allowed_tools:
      - "Read"
      - "Glob"
      - "Grep"
      - "Bash"

  codex:
    command: "codex"
    args:
      - "exec"
      - "--json"
      - "--dangerously-bypass-approvals-and-sandbox"
      - "--skip-git-repo-check"
    allowed_tools: []

  gemini:
    command: "gemini"
    args:
      - "-p"
      - "--output-format"
      - "json"
    allowed_tools: []

# Claude-mode configuration (activated with --claude flag)
# Defines Claude-specific agents, substitution rules, and phase overrides
claude_mode:
  # Claude agents for Claude-only mode (merge into agents map)
  agents:
    claude:
      command: "claude"
      args:
        - "-p"
        - "--output-format"
        - "stream-json"
        - "--verbose"
        - "--dangerously-skip-permissions"
      allowed_tools:
        - "Read"
        - "Glob"
        - "Grep"
        - "Write"
        - "Edit"
        - "Bash"
        - "WebSearch"
        - "WebFetch"
        - "Skill"
        - "Task"
      session_persistence:
        enabled: true
        strategy: conversation_resume

    claude-reviewer:
      command: "claude"
      args:
        - "-p"
        - "--output-format"
        - "stream-json"
        - "--verbose"
        - "--dangerously-skip-permissions"
      allowed_tools:
        - "Read"
        - "Glob"
        - "Grep"
        - "Bash"

  # Agent name substitutions when --claude is active
  substitutions:
    codex: claude
    gemini: claude

  # Override the reviewing phase to use specialized Claude reviewers
  # This replaces workflow.reviewing entirely when --claude is active
  reviewing:
    agents:
      - claude
      - agent: claude
        id: claude-practices
        prompt: |
          Focus your review on repository practices and code reuse:
          - Does the plan follow existing patterns and conventions in the codebase?
          - Are there existing utilities, helpers, or abstractions that should be reused?
          - Does the plan introduce unnecessary code duplication?
          - Are new abstractions justified, or should existing ones be extended?
          - Does the proposed structure align with the project's module organization?
      - agent: claude
        id: claude-completeness
        prompt: |
          Focus your review on completeness:
          - Does the plan cover every single requirement from the task description?
          - Are there any edge cases or scenarios that have been overlooked?
          - Does the plan include necessary error handling and validation steps?
          - Are all dependencies and integrations accounted for?
          - Is there a clear path for testing and verification of the implemented plan?
          - If any of these aspects are missing, reject the plan with detailed and specific feedback. Mention all missing elements and what you'd expect to see included.
    aggregation: any_rejects
    sequential: true

# Codex-mode configuration (for codex-only workflow)
# Defines Codex-specific agents, substitution rules, and phase overrides
codex_mode:
  # Codex agents for Codex-only mode (merge into agents map)
  agents:
    codex:
      command: "codex"
      args:
        - "exec"
        - "--json"
        - "--dangerously-bypass-approvals-and-sandbox"
        - "--skip-git-repo-check"
      allowed_tools: []

    codex-reviewer:
      command: "codex"
      args:
        - "exec"
        - "--json"
        - "--dangerously-bypass-approvals-and-sandbox"
        - "--skip-git-repo-check"
      allowed_tools: []

  # Agent name substitutions when codex-only mode is active
  substitutions:
    claude: codex
    gemini: codex

  # Override the reviewing phase to use only codex
  reviewing:
    agents:
      - codex
    aggregation: any_rejects
    sequential: false

  # Override implementation to use codex/codex-reviewer
  implementation:
    implementing:
      agent: codex
      max_turns: 100
    reviewing:
      agent: codex-reviewer

workflow:
  planning:
    agent: codex
    max_turns: 200

  # All three agents review in parallel
  # Supports both simple format (agent name string) and extended format (object with custom prompt)
  reviewing:
    agents:
      - claude
      - codex
      #- gemini

      # Extended format example: Run multiple Claude instances with different focuses
      # Uncomment below to add specialized review passes:
      #- agent: claude
      #  id: claude-security    # Display name for logs/UI (defaults to agent name)
      #  prompt: |              # Appended to system prompt for this instance
      #    Focus your review on security concerns:
      #    - Authentication and authorization
      #    - Input validation and sanitization
      #    - Secrets and credential handling
      #
      #- agent: claude
      #  id: claude-architecture
      #  prompt: |
      #    Focus your review on architectural concerns:
      #    - Code organization and modularity
      #    - Design patterns and best practices
      #    - Performance implications
    aggregation: any_rejects
    sequential: true

  # Note: Revision phase uses the planning agent automatically.
  # This enables session continuity when using Claude with session_persistence enabled.

# Failure handling policy
# Controls how transient failures and recovery are handled
failure_policy:
  max_retries: 2 # Maximum retry attempts for transient failures
  backoff_secs: 5 # Backoff multiplier in seconds between retries
  # Action when all reviewers fail after retries:
  # - abort: Stop workflow with error (default)
  # - save_state: Save state for later recovery in TUI mode
  # - continue_without_review: Proceed to revision phase without reviews
  on_all_reviewers_failed: abort

# Implementation workflow configuration
# Runs after plan approval to implement the plan using JSON-mode agents
implementation:
  enabled: true
  max_iterations: 3
  implementing:
    agent: codex
    max_turns: 100
  reviewing:
    agent: claude
    # max_turns uses agent default

# Optional: Post-implementation verification workflow
# Uncomment to enable verification after implementation
#verification:
#  enabled: true
#  max_iterations: 3
#  verifying:
#    agent: claude
#    max_turns: 10
#  fixing:
#    agent: claude
#    max_turns: 15
