# Multi-reviewer workflow configuration
# Uses Claude for planning and revising, with multiple reviewers

agents:
  claude:
    command: "claude"
    args:
      - "-p"
      - "--output-format"
      - "stream-json"
      - "--verbose"
      - "--dangerously-skip-permissions"

  codex:
    command: "codex"
    args:
      - "exec"
      - "--json"
      - "--dangerously-bypass-approvals-and-sandbox"
    allowed_tools: []

  gemini:
    command: "gemini"
    args:
      - "-p"
      - "--output-format"
      - "json"
    allowed_tools: []

workflow:
  planning:
    agent: codex
    max_turns: 200

  # All three agents review in parallel
  reviewing:
    agents:
      - claude
      - codex
      #- gemini
    # Use majority voting - 2 of 3 must reject to trigger revision
    aggregation: any_rejects

  revising:
    agent: claude
