# Multi-reviewer workflow configuration
# Uses Claude for planning and revising, with multiple reviewers

agents:
  claude:
    command: "claude"
    args:
      - "-p"
      - "--output-format"
      - "stream-json"
      - "--verbose"
      - "--dangerously-skip-permissions"

  codex:
    command: "codex"
    args:
      - "exec"
      - "--json"
      - "--dangerously-bypass-approvals-and-sandbox"
    allowed_tools: []

  gemini:
    command: "gemini"
    args:
      - "-p"
      - "--output-format"
      - "json"
    allowed_tools: []

workflow:
  planning:
    agent: codex
    max_turns: 200

  # All three agents review in parallel
  # Supports both simple format (agent name string) and extended format (object with custom prompt)
  reviewing:
    agents:
      - claude
      - codex
      #- gemini

      # Extended format example: Run multiple Claude instances with different focuses
      # Uncomment below to add specialized review passes:
      #- agent: claude
      #  id: claude-security    # Display name for logs/UI (defaults to agent name)
      #  prompt: |              # Appended to system prompt for this instance
      #    Focus your review on security concerns:
      #    - Authentication and authorization
      #    - Input validation and sanitization
      #    - Secrets and credential handling
      #
      #- agent: claude
      #  id: claude-architecture
      #  prompt: |
      #    Focus your review on architectural concerns:
      #    - Code organization and modularity
      #    - Design patterns and best practices
      #    - Performance implications
    # Use majority voting - 2 of 3 must reject to trigger revision
    aggregation: any_rejects

  # Note: Revision phase uses the planning agent automatically.
  # This enables session continuity when using Claude with session_persistence enabled.

# Failure handling policy
# Controls how transient failures and recovery are handled
failure_policy:
  max_retries: 2           # Maximum retry attempts for transient failures
  backoff_secs: 5          # Backoff multiplier in seconds between retries
  # Action when all reviewers fail after retries:
  # - abort: Stop workflow with error (default)
  # - save_state: Save state for later recovery in TUI mode
  # - continue_without_review: Proceed to revision phase without reviews
  on_all_reviewers_failed: abort

# Optional: Post-implementation verification workflow
# Uncomment to enable verification after implementation
#verification:
#  enabled: true
#  max_iterations: 3
#  verifying:
#    agent: claude
#    max_turns: 10
#  fixing:
#    agent: claude
#    max_turns: 15
